name: trex
description: "Clone of Flame trex game"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.16.0
  flame: ^1.29.0
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flame_lint: ^1.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
